---
title: "Length to age"
author: Darcy Webber
date: 13 March 2022
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Length to age}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `length2age` package makes use of `brms`. The package is designed to convert a length composition to an age composition, provided that there is some paired age-length data.

```{r echo=TRUE}
library(dplyr)
library(ggplot2)
library(brms)
library(stringr)
library(readr)
library(reshape2)
library(patchwork)
library(influ2)
library(bayesplot)
library(nzsf)
library(viridis)
library(influ2)
library(conflicted)

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

setwd("/home/darcy/Projects/length2age/vignettes")

theme_set(theme_bw())

options(mc.cores = 6)

criterion <- c("loo")

do_run <- FALSE

if (do_run) source("run_models.R")

load("full_ord.rda")
load("fit_ord.rda")
load("fit_more.rda")
```

First we import some data

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
# load("data/Darcy_HAK.ALK.data.SOP.otoliths.rdata")
load("../data/Darcy_HAK.ALK.data.ALL.otoliths.rdata")

d <- data2 %>%
  ungroup() %>%
  # filter(fyear %in% 2000:2010) %>%
  mutate(age = ordered(floor(age)), cyear = fyear, fyear = as.factor(fyear), month = as.factor(month))

glimpse(d)

table(data2$age)
table(data2$area)
table(data2$fyear)
table(data2$fmonth)
table(data2$month)
table(data2$origin)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
loo_ord <- loo_compare(full_1c, full_2c, full_3c, full_4c,
                       fit_0c, fit_1c, fit_2c, fit_3c, fit_4c, fit_5c, fit_6c, fit_7c, fit_8c, fit_9c, fit_10c, fit_11c, fit_12c,
                       fit_13c, fit_14c, fit_15c,
                       fit_2cv, fit_2r, fit_2s)

fit_best <- fit_14c # the best model run according to LOO IC
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
runs_list <- list(full_1c, full_2c, full_3c, full_4c, 
                  fit_0c, fit_1c, fit_2c, fit_3c, fit_4c, fit_5c, fit_6c, fit_7c, fit_8c, fit_9c, fit_10c, fit_11c, fit_12c,
                  fit_13c, fit_14c, fit_15c,
                  fit_2cv, fit_2r, fit_2s)
tb <- table_criterion(fits = runs_list, criterion = "loo")
write_csv(tb, file = "table_LOOIC.csv")
tb
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
fit <- fit_14c; p1 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- full_4c; p2 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_7c; p3 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_6c; p4 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_1c; p5 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_0c; p6 <- pp_check(object = fit, type = "bars", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
p1 + p2 + p3 + p4 + p5 + p6 + plot_layout(ncol = 2)
ggsave(filename = "pp_check_bars.png", width = 11, height = 14)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
fit <- fit_14c; p1 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- full_4c; p2 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_7c; p3 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_6c; p4 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_1c; p5 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
fit <- fit_0c; p6 <- pp_check(object = fit, type = "ecdf_overlay", ndraws = 100) + labs(x = "Age", title = gsub(".*\\~ ", "", as.character(fit$formula)[1]))
p1 + p2 + p3 + p4 + p5 + p6 + plot_layout(ncol = 2)
ggsave(filename = "pp_check_ecdf.png", width = 11, height = 14)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
yrep <- posterior_predict(fit_best, draws = 100)
ppc_bars_grouped(y = as.numeric(fit_best$data$age), yrep = yrep, group = d$fyear, facet_args = list(ncol = 3))
ggsave(filename = "pp_check_bars_year.png", width = 11, height = 16)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
yrep <- posterior_predict(fit_9c, draws = 100)
ppc_bars_grouped(y = as.numeric(fit_9c$data$age), yrep = yrep, group = d$fyear, facet_args = list(ncol = 3))
ggsave(filename = "pp_check_bars_year_2.png", width = 11, height = 16)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
# df <- get_conditional_smooths(x = fit, resolution = 100, smooths = "s(lat, long)", crs1 = st_crs(4326), crs2 = proj_nzsf())
df <- conditional_smooths(x = fit_best, resolution = 100, smooths = "s(lat, long)")[[1]] %>%
  rename(x = 2, y = 1) %>%
  st_as_sf(coords = c("x", "y"), crs = st_crs(4326)) %>%
  st_transform(crs = proj_nzsf())

pts <- fit_best$data %>%
  st_as_sf(coords = c("long", "lat"), crs = st_crs(4326)) %>%
  st_transform(crs = proj_nzsf())

ggplot() +
  geom_sf(data = pts, alpha = 0.5, shape = 4) +
  plot_raster(data = df, field = "estimate__", fun = mean, nrow = 100, ncol = 99) +
  scale_fill_viridis("s(lat, long)", alpha = 0.8) +
  plot_coast(resolution = "medium", fill = "black", colour = NA, size = 0.3) +
  plot_clip(x = df) +
  theme(axis.title = element_blank())

ggsave(filename = "best_model_conditional_smooth.png", width = 6, height = 7)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
fit1 <- fit_14c; p1 <- conditional_smooths(x = fit1, resolution = 100, smooths = "s(lat, long)")
fit2 <- full_4c; p2 <- conditional_smooths(x = fit2, resolution = 100, smooths = "s(lat, long)")
fit3 <- full_2c; p3 <- conditional_smooths(x = fit3, resolution = 100, smooths = "t2(lat, long)")
fit4 <- fit_15c; p4 <- conditional_smooths(x = fit4, resolution = 100, smooths = 's(lat, long, bs = "gp")')

plot(p1, plot = FALSE)[[1]] + labs(title = gsub(".*\\~ ", "", as.character(fit1$formula)[1])) +
  plot(p2, plot = FALSE)[[1]] + labs(title = gsub(".*\\~ ", "", as.character(fit2$formula)[1])) +
  plot(p3, plot = FALSE)[[1]] + labs(title = gsub(".*\\~ ", "", as.character(fit3$formula)[1])) +
  plot(p4, plot = FALSE)[[1]] + labs(title = gsub(".*\\~ ", "", as.character(fit4$formula)[1]))

ggsave(filename = "conditional_smooth_comparisons.png", width = 11, height = 14)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
conditional_effects(x = fit_best, effects = "length", categorical = TRUE)
ggsave(filename = "best_model_conditional_effect_length.png", width = 10, height = 6)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
conditional_effects(x = full_4c, effects = "origin", categorical = TRUE)
ggsave(filename = "best_model_conditional_effect_origin.png", width = 10, height = 6)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
conditional_effects(x = fit_best, effects = "cyear", categorical = TRUE)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
conditional_effects(x = fit_best, effects = "month", categorical = TRUE)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
newdata <- fit_best$data %>% 
  mutate(age = as.integer(as.character(age))) %>%
  sample_n(size = 2000) %>%
  droplevels()

head(newdata)
dim(newdata)

# ppred <- fitted(object = fit_best, newdata = newdata, summary = TRUE)
ppred <- predict(object = fit_best, newdata = newdata, summary = TRUE)
# ppred <- posterior_epred(object = fit_best, newdata = newdata, summary = TRUE)

head(ppred)
dim(ppred)

df <- data.frame(age = sort(unique(as.integer(fit_best$data$age))), 
                 pred =  colSums(ppred))

table(newdata$age)
table(fit_best$data$age)

ggplot() +
  geom_point(data = newdata, aes(x = age), fill = "lightblue", colour = "black", stat = "count") +
  geom_line(data = df, aes(x = age, y = pred), colour = "red")
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
# devtools::install_github("davidsjoberg/ggsankey")
# library(ggsankey)
# 
# example_dat <- mtcars %>%
#   make_long(cyl, vs, am, gear, carb) # function in ggsankey to format data correctly
# 
# # get this to work with age/length
# 
# ggplot(example_dat,
#        aes(x = x, 
#                next_x = next_x, 
#                node = node, 
#                next_node = next_node,
#                fill = factor(node))) +
#    geom_sankey(flow.alpha = .6) +
#   theme_minimal()
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
# Fit brms models ----

# First model length and age, specifiy a different sigma for each age
# fit1 <- brm(bf(length ~ age, sigma ~ age), 
#             data = data, 
#             family = gaussian())
# 
# conditional_effects(x = fit1)
# 
# # Then we would take the estimates from this and feed them into the mixture model - this could be done by fixing values below or specifying priors
# mix <- mixture(gaussian, nmix = n_age, order = TRUE)
# 
# formula1 <- bf(length ~ 1)
# 
# # Fixing values
# pfix <- list()
# pfix[1:(n_age*2)] <- c(mu_length, sd_length)
# names(pfix) <- c(paste0("mu", 1:n_age), paste0("sigma", 1:n_age))
# formula2 <- formula1
# formula2$pfix <- pfix
# 
# # Specifying priors
# priors <- get_prior(formula = formula1, data = data, family = mix)
# sigma_pos <- str_detect(priors$class, "sigma")
# sigma_names <- priors[sigma_pos, "class"]
# sigma_age <- parse_number(sigma_names)
# sigma_order <- match(paste0("sigma", sort(sigma_age)), priors$class)
# priors$prior[sigma_order] <- paste0("normal(", mu_length, ", ", sd_length, ")")
# 
# # priors <- c(prior(normal(3, 0.01), class = "Intercept", dpar = "mu1"),
# #             prior(normal(4.75, 0.01), class = "Intercept", dpar = "mu2"),
# #             prior(normal(6.5, 0.01), class = "Intercept", dpar = "mu3"),
# #             prior(normal(8.25, 0.01), class = "Intercept", dpar = "mu4"),
# #             prior(normal(10, 0.01), class = "Intercept", dpar = "mu5"),
# #             prior(normal(0.8, 0.01), class = "sigma1"),
# #             prior(normal(0.8, 0.01), class = "sigma2"),
# #             prior(normal(0.8, 0.01), class = "sigma3"),
# #             prior(normal(0.8, 0.01), class = "sigma4"),
# #             prior(normal(0.8, 0.01), class = "sigma5"),
# #             prior(dirichlet(1), class = "theta"))
# 
# fit2_p <- brm(formula = formula1, data = data, prior = priors, family = mix, sample_prior = "yes")
# fit2_f <- brm(formula = formula2, data = data, family = mix)
# 
# # If my theory is correct, then the simplex of theta's should be the same as the proportions at age
# summary(fit2a)
# prop <- n_samples / sum(n_samples)
# prop
# 
# # Do a hypothesis test ----
# hyp <- paste0("theta", 1:n_age, " = ", prop)
# test <- hypothesis(x = fit2a, hypothesis = hyp, class = NULL)
# test
# plot(test)
```
