---
title: "Length to age"
author: Darcy Webber
date: 29 May 2022
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Length to age}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `length2age` package makes use of `brms`. The package is designed to:

* model length composition or length frequency (LF) data
* scale LF data
* convert LF data to an age composition, provided that there is some paired age-length data.

```{r echo=TRUE}
library(dplyr)
library(ggplot2)
library(brms)
library(stringr)
library(readr)
library(reshape2)
library(conflicted)

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("ar", "brms")

theme_set(theme_bw())
options(mc.cores = 6)
criterion <- c("loo")

do_run <- FALSE
```

First we simulate some data

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
n_age <- 10
n_sims <- 4000
n_samples <- 2000 # the number of aged individuals

# Define the distribution of length for each age ----
von_bertalanffy <- function(age, Linf, k, t0) {
  length <- Linf * (1.0 - exp(-k * (age - t0)))
  return(length)
}

mu_length <- von_bertalanffy(age = 1:n_age, Linf = 100, k = 0.5, t0 = -0.5)
cv_length <- rep(0.05, n_age)
sd_length <- cv_length * mu_length

df <- data.frame(age = 1:n_age, length = mu_length, sd = sd_length)

ggplot(data = df, aes(x = age, y = length)) +
  geom_line() +
  geom_pointrange(aes(ymin = length - sd, ymax = length + sd)) +
  labs(x = "Age")
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
# Simulate a paired age-length data set ----
count <- c(1, 1, 7, 40, 60, 50, 30, 40, 12, 10, 9, 10, 2, 2, 1, 1, 4, 3, 1, 1)
prob <- count / sum(count)
df <- data.frame(age = 1:n_age, count = rmultinom(n = 1, size = n_sims, prob = prob))
age_sims <- rep(df$age, df$count)

length_sims <- sapply(age_sims, function(x) rnorm(1, mean = mu_length[x], sd = sd_length[x]))

data <- data.frame(age = as.integer(age_sims), length = length_sims)

i <- sample(x = 1:nrow(data), size = n_samples)
data_age <- data[i,]
data_lf <- data[-i,]

data <- data_age %>%
  mutate(age = ordered(age))
glimpse(data)

ggplot(data = data, aes(x = age)) +
  geom_bar()

ggplot(data = data_lf) +
  geom_histogram(aes(x = length, fill = factor(age))) +
  labs(x = "Length (cm)", fill = "Age")
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
if (do_run) {
  fit_ord1 <- brm(age ~ length, data = data, family = cumulative("logit", threshold = "flexible"))
  fit_ord2 <- brm(age ~ s(length), data = data, family = cumulative("logit", threshold = "flexible"))
  # fit_ord3 <- brm(age ~ t2(length), data = data, family = cumulative("logit", threshold = "flexible"))
  # fit_ord4 <- brm(age ~ s(length, k = 3), data = data, family = cumulative("logit", threshold = "flexible"))
  # fit_ord5 <- brm(age ~ s(length, bs = "cr"), data = data, family = cumulative("logit", threshold = "flexible"))
  # fit_ord6 <- brm(age ~ t2(length, bs = "ts"), data = data, family = cumulative("logit", threshold = "flexible"))

  fit_ord1 <- add_criterion(fit_ord1, criterion = criterion)
  fit_ord2 <- add_criterion(fit_ord2, criterion = criterion)
  # fit_ord3 <- add_criterion(fit_ord3, criterion = criterion)
  # fit_ord4 <- add_criterion(fit_ord4, criterion = criterion)
  # fit_ord5 <- add_criterion(fit_ord5, criterion = criterion)
  # fit_ord6 <- add_criterion(fit_ord6, criterion = criterion)

  save(data,
       fit_ord1, fit_ord2, 
       # fit_ord3, fit_ord4, fit_ord5, fit_ord6,
       file = "fit_ord.rda")
} else {
  load("fit_ord.rda")
}

loo_compare(fit_ord1, fit_ord2)
```

```{r echo=TRUE, fig.height=6, fig.width=9, message=FALSE}
conditional_smooths(x = fit_ord2)
conditional_effects(x = fit_ord1, effects = "length", categorical = TRUE)

pp_check(object = fit_ord1, type = "bars", ndraws = 100) + 
  labs(x = "Age")

pp_check(object = fit_ord2, type = "ecdf_overlay", ndraws = 100) + 
  labs(x = "Age")

newdata <- data_lf %>% select(-age)
head(newdata)
dim(newdata)

fit <- fit_ord2
# ppred <- fitted(object = fit_ord, newdata = newdata, summary = TRUE)
ppred <- predict(object = fit, newdata = newdata, summary = TRUE)
# ppred <- posterior_epred(object = fit_ord, newdata = newdata, summary = TRUE)
head(ppred)
dim(ppred)

df <- data.frame(age = 1:n_age, pred =  colSums(ppred))

ggplot(data = data_lf) +
  geom_histogram(aes(x = age), binwidth = 1, fill = "lightblue", colour = "black") +
  geom_point(data = df, aes(x = age, y = pred), colour = "red") +
  labs(x = "Age")
```
